/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ILiquidBookEngine {
    function getOrder(uint256 id) external view returns (address, uint256, uint256, bool, bool);

    function getOrderTick(uint256 tick) external view returns (uint256, uint256, uint256);

    function placeLimitOrder(uint256 tick, uint256 amount, bool is_buy) external returns (uint256);

    function cancelOrder(uint256 id) external;
}
