/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ILiquidBookEngine {
    function initialize(address tick_manager_address, address order_manager_address) external;

    function executeMatch((uint256,uint256,uint256)[] memory valid_orders, uint256 incoming_order_quantity) external returns (uint256);

    function matchMarketOrder(uint256 incoming_order_tick, uint256 incoming_order_volume, address incoming_order_user, bool incoming_order_is_buy, bool incoming_order_is_market) external;
}
