/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface BitmapManager {
    event SetCurrentTick(uint256 indexed tick);
    
    event FlipTick(int32 indexed tick);

    function position(int32 tick) external returns (int16, uint8);

    function getCurrentTick() external view returns (uint256);

    function setCurrentTick(uint256 tick) external returns (uint256);

    function topNBestTicks(bool is_buy) external view returns (uint256[] memory);

    function flip(int32 tick) external returns (int16, uint8);

    function getBitmap(int16 index) external;

    function nextTick(int32 tick, bool lte) external view returns (int32, bool);
}