/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

contract BitmapManager {
    event SetCurrentTick(int128 indexed tick);
    
    event FlipTick(int32 indexed tick);

    function position(int32 tick) external returns (int16, uint8);

    function getCurrentTick() external view returns (int128);

    function setCurrentTick(int128 tick) external returns (int128);

    function topNBestTicks(bool is_buy) external view returns (int128[] memory);

    function flip(int32 tick) external returns (int16, uint8);

    function getBitmap(int16 index) external;

    function nextTick(int32 tick, bool lte) external view returns (int32, bool);
}