/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

contract LiquidBookEngine {
    event PlaceOrder(address indexed user, uint256 indexed tick, bool indexed is_buy, uint256 volume);

    function initialize(address tick_manager_address, address order_manager_address, address bitmap_manager_address, address matcher_manager_address) external;

    function placeOrder(uint256 incoming_order_tick, uint256 incoming_order_volume, address incoming_order_user, bool incoming_order_is_buy, bool incoming_order_is_market) external;
}