/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

contract Matcher {
    function initialize(address bitmap_manager_address, address order_manager_address) external;

    function execute((uint256,uint256,uint256)[] memory valid_orders, uint256 incoming_order_volume, uint256 tick_value, uint256 tick_volume) external returns (uint256);
}