/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IOrderManager {
    event InsertOrder(address indexed user, int128 indexed tick, uint256 indexed order_index, bool is_buy, uint256 volume);

    event UpdateOrder(int128 indexed tick, uint256 indexed order_index, uint256 volume);

    function initialize(address engine_address, address bitmap_manager_address, address tick_manager_address) external;

    function insertOrder(int128 tick, uint256 volume, address user, bool is_buy) external returns (uint256);

    function updateOrder(int128 tick, uint256 tick_volume, uint256 volume, uint256 order_index) external;

    function readOrder(int128 tick, uint256 order_index) external view returns (address, uint256);

    function writeOrder(int128 tick, uint256 order_index, address user, uint256 volume) external;

    function deleteOrder(int128 tick, uint256 order_index) external;

    function encodeOrderKey(int128 tick, uint256 order_index) external view returns (uint8[] memory);

    function encodeOrderData(address user, uint256 volume) external view returns (uint8[32] memory);

    function decodeOrderData(uint8[] memory encoded) external view returns (address, uint256);
}
