/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IPoolManager {
    event PoolInitialized(address indexed pool_address, address indexed asset_token, address indexed stable_token, int128 current_tick, uint256 lot_size);

    function initialize(address balance_manager) external;

    function addPool(address pool_address, address asset_token, address stable_token, address engine_manager, address bitmap_manager, int128 current_tick, uint256 lot_size) external;

    function placeOrder(address pool_address, uint256 incoming_order_volume, int128 incoming_order_tick, bool incoming_order_is_buy, bool incoming_order_is_market) external;
}
