/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ITickManager {
    event SetTickData(int128 indexed tick, bool indexed is_buy, uint256 indexed volume, bool is_existing_order);

    function initialize(address engine_address, address bitmap_manager_address, address order_manager_address) external;

    function setTickData(int128 tick, uint256 volume, bool is_buy, bool is_existing_order) external;

    function getTickData(int128 tick) external view returns (uint256, uint256, uint256, bool);
}
