/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ILendingExecute {
    function initialize(address lending_address) external;

    function deposit(uint256 amount) external;

    function withdraw(uint256 amount) external;
}
