/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IBitmapStorage {
    function position(int32 tick) external returns (int16, uint8);

    function flip(int32 tick) external returns (int16, uint8);

    function getBitmap(int32 tick) external returns (uint256);

    function nextTick(int32 tick, bool lte) external returns (int32, bool);

    function testBitmap() external;
}
