/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IOrderBook {
    function flip(int32 tick) external;

    function nextTick(int32 tick, bool lte) external;

    function getBitmap(int16 index) external;

    function testBitmap() external;
}
